branch-defaults:
  master:
    environment: Multiplegoservices-env
deploy:
  artifact: build/bundle.zip
global:
  application_name: MultipleGoServices
  branch: master
  default_ec2_keyname: null
  default_platform: Multi-container Docker 17.12.1-ce (Generic)
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
